# Generated by Django 2.2.5 on 2019-09-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='Branch',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
